export default [
	{
		id: 'start_unlimited',
		name: 'Start Unlimited',
		details: [
			'5G Nationwide',
			'4G LTE data',
			'Disney+ for 6 months on us',
			'discovery+ for 6 months on us',
			'Apple Arcade for 6 months on us',
			'Google Play Pass for 6 months on us',
			'Apple Music for 6 months on us',
		],
	},
	{
		id: 'play_more',
		name: 'Play More Unlimited',
		details: [
			'5G Ultra Wideband',
			'5G Nationwide',
			'Premium Network Access',
			'4G LTE data',
			'Unlimited mobile hotspot 15 GB of 5G Nationwide / 4G LTE data',
			'Hulu, Disney+ and ESPN included',
			'discovery+ for 12 months on us',
			'Apple Arcade for 12 months on us',
			'Google Play Pass for 12 months on us',
			'Apple Music for 6 months on us',
		],
	},
	{
		id: 'do_more',
		name: 'Do More Unlimited',
		details: [
			'5G Ultra Wideband',
			'5G Nationwide',
			'Premium Network Access',
			'4G LTE data',
			'Unlimited mobile hotspot 15 GB of 5G Nationwide / 4G LTE data',
			'Disney+ for 6 months on us',
			'discovery+ for 6 months on us',
			'Apple Arcade for 6 months on us',
			'Google Play Pass for 6 months on us',
			'Apple Music for 6 months on us',
			'600 GB of Verizon Cloud Storage',
			'50% iff select connected device plans',
		],
	},
	{
		id: 'get_more',
		name: 'Get More Unlimited',
		details: [
			'5G Ultra Wideband',
			'5G Nationwide',
			'Premium Network Access',
			'4G LTE data',
			'Unlimited mobile hotspot 30 GB of 5G Nationwide / 4G LTE data',
			'Hulu, Disney+ and ESPN included',
			'discovery+ for 12 months on us',
			'Apple Arcade for 12 months on us',
			'Google Play Pass for 12 months on us',
			'Apple Music included',
			'600 GB of Verizon Cloud Storage',
			'50% iff select connected device plans',
		],
	},
	{
		id: 'just_kids',
		name: 'Just Kids',
		details: [
			'5G Nationwide',
			'4G LTE data',
			'Unlimited data at 5Mbps',
			'Unlimited Talk & Text up to 20 contacts',
		],
	},
];
