export const ADD_REFEREE = 'ADD_REFEREE';
export const GET_REFEREE = 'GET_REFEREE';
export const GET_REFEREES = 'GET_REFEREES';
export const REFEREE_LOADING = 'REFEREE_LOADING';
export const REFEREE_ERROR = 'REFEREE_ERROR';
