export const ADD_REFERRAL = 'ADD_REFERRAL';
export const GET_REFERRAL = 'GET_REFERRAL';
export const GET_REFERRALS = 'ADD_REFERRALS';
export const UPDATE_REFERRAL = 'UPDATE_REFERRAL';
export const LOADING_REFERRAL = 'ADD_REFERRAL';
export const REFERRAL_ERROR = 'REFERRAL_ERROR';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
