export const SIGN_IN = 'SIGN_IN'
export const SIGN_UP = 'SIGN_UP'
export const USER_LOADING = 'USER_LOADING'
export const SIGN_OUT = 'SIGN_OUT'
export const USER_ERROR = 'USER_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'